config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'docs#new'
  
  resources :users
  resources :settings
  resources :docs
  resources :password_resets, only: %i[new create edit update]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    return unless user && user&.admin? # 管理者じゃなかったらこのメソッドを抜ける

    can :access, :rails_admin # 管理者画面のアクセス許可
    can :manage, :all # 管理権限許可
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
  
  mount_uploader :main, ImageUploader
  mount_uploader :pptx, ImageUploader
end

app/models/setting.rb
class Setting < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  validates :reset_password_token, uniqueness: true, allow_nil: true
  # validates :email, uniqueness: true, presence: true
  # validates :password, presence: true, on: :create
  # VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]{8,32}\z/i.freeze
  # validates :password, format: { with: VALID_PASSWORD_REGEX, massege: 'は半角英数を両方含む必要があります' }, on: :create
  # validates :password, length: { minimum: 8 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  has_one :setting
  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :require_login
  #sorceryが作成するメソッド。ログインしてない時not_authenticatedメソッドを発火する
  helper_method :exist_setting

  
  protected

  
  def not_authenticated
    redirect_to login_url
  end

  
  private
  def exist_setting
    @exist_setting = Setting.find_by(user_id: current_user.id)
  end

  def set_host_from_request
    ActionMailer::Base.default_url_options = { host: request.host_with_port }
  end
  
  def not_authenticated
    flash[:info] = 'ログインしてください'
    redirect_to main_app.login_path #main_appのプレフィックスをつける
  end
  
  # def common_user
  #   common_user = User.find_by(user_id: current_user.id)
  # end
  
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController

  def new
    @doc = Doc.new
  end
  
  def create
    @doc = Doc.new(doc_params)
    if @doc.save
      # binding.pry
      # FileUtils.cp(doc_params[:pptx].path, "/tmp/temp.pptx")
      RequestMailer.with(doc: @doc.id).request_email.deliver_later
      RequestMailer.with(doc: @doc.id).thanks_email.deliver_later
      logger.info("メールアクションの完了")
      redirect_to root_path
    else
      redirect_to new_setting_path
    end
  end

  def edit
  end

  def update
  end

  private
  def doc_params
    params.require(:doc).permit(:user_id, :main, :sheet, :title, :size, :deadline, :detail, :pptx, :g_slide, :content, :scene, :shower, :deplication, :format, :main_color, :sub_color, :font).merge(user_id: current_user.id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_action :require_login

  def new

  end

  def create
    @user = User.find_by_email(params[:email])
    if @user
      @user.deliver_reset_password_instructions!
    else
      return  redirect_to(new_password_reset_path, :notice => 'This email is not correct')
    end
    return redirect_to(root_path, :notice => 'Instructions have been sent to your email.')
  end
    
  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end
    # binding.pry
  end
      
  
  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end


    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.change_password!(params[:user][:password])
      redirect_to(root_path, :notice => 'Password was successfully updated.')
    else
      render :action => "edit"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    logout
    redirect_to root_path
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  def new
    @setting = Setting.new
  end
  
  def create
    @setting = Setting.new(setting_params)
    if @setting.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @setting = Setting.where(user_id: current_user.setting.user_id)
    # binding.pry
  end

  def update
    @setting = Setting.where(user_id: current_user.setting.user_id)
    if @setting.update(setting_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def setting_params
    params.require(:setting).permit(:user_id, :font, :main_color, :sub_color).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :require_login, only: [:create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :company, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/docs/new.html.erb
<div class="doc-wrap">

  <div class="doc-form_frame">
    <%= form_with model: @doc, class:"doc-form", id:"js-doc-form" do |f| %>
      <dl class="doc-form_item">
        <dt class="doc-form_item-title">PDFアップロード</dt>
        <dd>
          <label for="js-up-file" class="doc-form_item-desc-file-label" id="js-file-label"><%= image_tag 'pdf.png', {class: 'doc-form_icon'} %>PDFをアップロードする</label>
          <%= f.file_field :main, class:"doc-form_item-desc doc-form_item-desc-file", id:"js-up-file" %>
        </dd>
      </dl>

      <div class="doc-form_item-file-flex">
      
        <dl class="doc-form_item doc-form_item-file-w">
          <dt class="doc-form_item-title">PowerPoitntアップロード</dt>
          <dd>
            <label for="js-up-file-pptx" class="doc-form_item-desc-file-label" id="js-file-label-pptx"><%= image_tag 'powerpoint.png', {class: 'doc-form_icon'} %>pptxをアップロードする</label>
            <%= f.file_field :pptx, class:"doc-form_item-desc doc-form_item-desc-file", id:"js-up-file-pptx" %>
          </dd>
        </dl>

        <dl class="doc-form_item doc-form_item-file-w">
          <dt class="doc-form_item-title">Googleスライドアップロード</dt>
          <dd><%= f.text_field :g_slide, class:"doc-form_item-desc-g_slide doc-form_item-desc-text", placeholder:"共有用リンクの貼り付け" %></dd>
        </dl>
      
      </div>


      <dl class="doc-form_item">
        <dt class="doc-form_item-title">資料ジャンル</dt>
        <dd><%= f.select :title, [
        ["会社紹介資料", "会社紹介資料"],
        ["ウェビナー資料", "ウェビナー資料"],
        ["提案資料", "提案資料"],
        ["採用ピッチ資料", "採用ピッチ資料"],
        ["サービス紹介資料", "サービス紹介資料"],
        ["ホワイトペーパー", "ホワイトペーパー"],
        ["株主向けIR資料", "株主向けIR資料"],
        ["社内向け資料", "社内向け資料"],
        ["その他", "その他"]
        ], include_blank: "選択して下さい" %></dd>
      </dl>

      <dl class="doc-form_item">
        <dt class="doc-form_item-title">資料枚数(自動計算)</dt>
        <dd><span class="doc-form_item-desc doc-form_item-desc-sheet" id="js-pdf-count"></span>枚</dd>
        <%= f.number_field :sheet, class:"doc-form_item-desc-sheet-hidden", id:"js-hidden-pdf-count" %>
      </dl>

      <dl class="doc-form_item">
        <dt class="doc-form_item-title">納期</dt>
        <dd><%= f.date_field :deadline, class:"doc-form_item-desc doc-form_item-desc-text", id:"js-deadline-input" %></dd>
      </dl>

      <div class="doc-form_line"></div>

      <dl class="doc-form_item">
        <dt class="doc-form_item-title">資料の内容・概要</dt>
        <dd><%= f.text_area :content, class:"doc-form_item-desc doc-form_item-desc-textarea", placeholder:"(例)セールスの際にサービスの内容、サービスを利用した時のメリットを図解を用いて説明している" %></dd>
      </dl>

      <dl class="doc-form_item">
        <dt class="doc-form_item-title">資料の活用場面</dt>
        <dd><%= f.text_field :scene, class:"doc-form_item-desc doc-form_item-desc-text", placeholder:"(例)WEB商談時の提案の時に" %></dd>
      </dl>

      <dl class="doc-form_item">
        <dt class="doc-form_item-title">資料を見せる相手</dt>
        <dd><%= f.text_field :shower, class:"doc-form_item-desc doc-form_item-desc-text", placeholder:"(例)新規クライアント向け" %></dd>
      </dl>

      <dl class="doc-form_item">
        <dt class="doc-form_item-title">ページ内で重複している内容の削除や調整をしてもよろしいですか？</dt>
        <dd class="doc-form_item-desc doc-form_item-desc-size">
          <div>
            <%= f.radio_button :deplication, "OK" %>
            <%= f.label :deplication, "OK", {style: "display: inline-block;"} %>
          </div>
          <div>
            <%= f.radio_button :deplication, "NG" %>
            <%= f.label :deplication, "NG", {style: "display: inline-block;"} %>
          </div>
        </dd>
      </dl>

      <dl class="doc-form_item">
        <dt class="doc-form_item-title">サイズ</dt>
        <dd class="doc-form_item-desc doc-form_item-desc-size">
          <div>
            <%= f.radio_button :size, "16:9" %>
            <%= f.label :size, "１６：９", {style: "display: inline-block;"} %>
          </div>
          <div>
            <%= f.radio_button :size, "4:3" %>
            <%= f.label :size, "４：３", {style: "display: inline-block;"} %>
          </div>
        </dd>
      </dl>

      <dl class="doc-form_item">
        <dt class="doc-form_item-title">納品形式</dt>
        <dd class="doc-form_item-desc doc-form_item-desc-size">
          <div>
            <%= f.radio_button :format, "PowerPoint" %>
            <%= f.label :format, "PowerPoint", {style: "display: inline-block;"} %>
          </div>
          <div>
            <%= f.radio_button :format, "Googleスライド" %>
            <%= f.label :format, "Googleスライド", {style: "display: inline-block;"} %>
          </div>
        </dd>
        <p><b>　※どちらもPDFと共に納品いたします</b></p>
      </dl>


      <dl class="doc-form_item">
        <dt class="doc-form_item-title">フォント</dt>
        <dd class="doc-form_item-desc doc-form_item-desc-size" style="flex-wrap:wrap">
          <div>
            <%= f.radio_button :font, "游ゴシック" %>
            <%= f.label :font, "游ゴシック", {style: "display: inline-block;"} %>
          </div>
          <div>
            <%= f.radio_button :font, "メイリオ" %>
            <%= f.label :font, "メイリオ", {style: "display: inline-block;"} %>
          </div>
          <div>
            <%= f.radio_button :font, "Meiryo UI" %>
            <%= f.label :font, "Meiryo UI", {style: "display: inline-block;"} %>
          </div>
          <div>
            <%= f.radio_button :font, "コーポレートロゴ" %>
            <%= f.label :font, "コーポレートロゴ", {style: "display: inline-block;"} %>
          </div>
          <div>
            <%= f.radio_button :font, "おまかせ" %>
            <%= f.label :font, "おまかせ", {style: "display: inline-block;"} %>
          </div>
        </dd>
      </dl>

      <div class="doc-form_color-frame">

        <p class="doc-form_color-frame-title">※色の指定がなければ元の資料から抜粋します</p>

        <dl class="doc-form_color">
          <dt class="doc-form_title">
            <p class="doc-form_title-text">メインカラー</p>
            <input type="color" class="doc-form_title-color" id="js-main-pick">
          </dt>
          <dd><%= f.text_field :main_color, class:"doc-form_desc", id:"js-main-code" %></dd>
        </dl>

        <dl class="doc-form">
          <dt class="doc-form_title">
            <p class="doc-form_title-text">アクセントカラー</p>
            <input type="color" class="doc-form_title-color" id="js-sub-pick">
          </dt>
          <dd><%= f.text_field :sub_color, class:"doc-form_desc", id:"js-sub-code" %></dd>
        </dl>

      </div>

      <dl class="doc-form_item">
        <dt class="doc-form_item-title">依頼内容詳細</dt>
        <dd><%= f.text_area :detail, class:"doc-form_item-desc doc-form_item-desc-textarea" %></dd>
      </dl>

      <p class="doc-form_atention">
      上記依頼内容、右記の見積もりで良ければ下のボタンを押してください
      </p>

      <%= f.submit "資料作成を依頼する", class:"doc-submit", id:"js-doc-submit" %>

      <p class="doc-form_atention" style="opacity:0;" id="js-request-comp">依頼が完了しました！</p>

    <% end %>
  </div>

  <div class="doc-preview">
    <p class="doc-preview_title">見積書プレビュー</p>
    <div class="doc-preview_frame">

      <div id="js-canvas" class="doc-preview_frame-main">

        <p class="preview_title">見積書</p>
        <div class="preview_top-wrap">
          <div class="preview_top-wrap-left">
            <p class="preview_top-wrap-left-text"><%= current_user.company %>御中</p>
          </div>
          <div class="preview_top-wrap-right">
            <div class="preview_top-wrap-right-image-frame">
              <%= image_tag 'cone-logo.jpg', class:"preview_top-wrap-right-image" %>
            </div>
            <div class="preview_top-wrap-right-txtbox">
              <%= image_tag 'cone-shadow.jpg', class:"preview_top-wrap-right-shadow" %>
              <p class="preview_top-wrap-right-txt preview_top-wrap-right-txt-mb ">株式会社Cone</p>
              <p class="preview_top-wrap-right-txt">〒530-0027</p>
              <p class="preview_top-wrap-right-txt">大阪府大阪市北区堂山町1-5</p>
              <p class="preview_top-wrap-right-txt preview_top-wrap-right-txt-mb ">梅田三共ビル7階</p>
              <p class="preview_top-wrap-right-txt">見積書番号:2022060499</p>
              <p class="preview_top-wrap-right-txt">発行日:<%= Date.today.strftime("%Y/%m/%d") %></p>
            </div>
          </div>
        </div>

        <p class="preview_item-name">件名:【slidebox】資料作成代行費用</p>

        <p class="preview_mitumori">御見積金額 <span id="js-show-money"></span> 円</p>

        <div class="preview_breakdown">

          <dl class="preview_breakdown-item preview_breakdown-item-w7">
            <dt class="preview_breakdown-title">品目</dt>
            <dd class="preview_breakdown-desc" id="js-doc-title-preview"></dd>
          </dl>

          <dl class="preview_breakdown-item preview_breakdown-item-w1">
            <dt class="preview_breakdown-title">単価</dt>
            <dd class="preview_breakdown-desc">3,000</dd>
          </dl>

          <dl class="preview_breakdown-item preview_breakdown-item-w1">
            <dt class="preview_breakdown-title">数量</dt>
            <dd class="preview_breakdown-desc" id="js-set-sheet"></dd>
          </dl>

          <dl class="preview_breakdown-item preview_breakdown-item-w1">
            <dt class="preview_breakdown-title">価格</dt>
            <dd class="preview_breakdown-desc" id="js-price"></dd>
          </dl>
        
        </div>

        <div class="preview-detail">

          <div class="preview-detail_wrap">
            <p class="preview-detail_title">小計</p>
            <p class="preview-detail_desc"><span id="js-subtotal"></span> 円</p>
          </div>

          <div class="preview-detail_wrap">
            <p class="preview-detail_title">消費税</p>
            <p class="preview-detail_desc"><span id="js-tax"></span> 円</p>
          </div>

          <div class="preview-detail_wrap">
            <p class="preview-detail_title">合計</p>
            <p class="preview-detail_desc"><span id="js-total"></span> 円</p>
          </div>

        </div>

        <p style="margin-bottom: 0;">備考</p>
        <div class="preview_remarks">
          <p style="margin-bottom: 0;">【納期】<span id="js-deadline-output"></span></p>
          <p style="margin-bottom: 10px;">【仕様】頂戴する資料に基づく</p>
          <p style="margin-bottom: 0;">・本案件の申し込み後のキャンセルに関してはキャンセル費として申し込み金額の全額が発生いたします。</p>
        </div>


      </div>

      <button id="js-canvas-btn" class="preview_button">見積書をダウンロードする</button>

    </div>
  </div>
  
</div>

app/views/homes/index.html.erb
<h1>Homes#index</h1>
<p>Find me in app/views/homes/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>slidebox</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
 
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% if current_page?(root_path) %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <% end %>
    
  </head>

  <body>
    <% unless current_page?(login_path) || current_page?(new_password_reset_path) || (@token && current_page?(:controller => 'password_resets', :action => 'edit', :id => @token)) %>
      <%= render 'partial/navbar' %>

      <p class="sp-attention">1200px以下のデバイスには対応しておりません。</p>
      <div class="c-inner">
      
        <div class="c-wrap">
        
          <aside class="c-sidebar">
            <%= link_to root_path, class:'c-sidebar_item' do %>
              <i class="fa fa-plus c-sidebar_icon"></i><span>新規作成</span>
            <% end %>
            <!--<% if exist_setting == nil %>
              <%= link_to new_setting_path, class:'c-sidebar_item' do %>
                <i class="fa fa-plus c-sidebar_icon"></i><span>設定</span>
              <% end %>
            <% else %>
              <%= link_to edit_setting_path(id: exist_setting.user_id), class:'c-sidebar_item' do %>
                <i class="fa fa-plus c-sidebar_icon"></i><span>設定</span>
              <% end %>
            <% end %>-->
            <%= link_to edit_user_path(id: current_user.id), class:'c-sidebar_item' do %>
              <i class="fa fa-plus c-sidebar_icon"></i><span>アカウント</span>
            <% end %>

          </aside>

          <div class="c-main">

            <%= yield %>

          </div>

        
        </div>

      </div>
    

    <% else %>

      <%= yield %>

    <% end %>
    



    <%= javascript_pack_tag 'home/common' %>

    <% if current_page?(root_path) %>
    <script src="https://cdn.jsdelivr.net/npm/html-to-image@1.7.0/dist/html-to-image.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.min.js"></script>
    <%= javascript_pack_tag 'home/toPdf' %>
    <%= javascript_pack_tag 'home/preview' %>
    <% end %>


  </body>
</html>

app/views/partial/_navbar.html.erb
<div class="p-nav">
  <nav class='p-navbar'>
    <%= link_to root_path, {class: 'p-nav-link'} do %>
      <%= image_tag 'logo.svg', {class: 'p-nav-img'} %>
    <% end %>
    <div class="p-nav-right">
      <p class="p-nav-right_name"><%= current_user.name %></p>
      <p class="p-nav-right_setting" id="js-setting">設定</p>
    </div>

    <div class="overlay" id="overLay"></div>

    <ul class="p-nav-global" id="navGlobal">
      <div class="p-nav-global-profile">
        <p class="p-nav-global-company"><%= current_user.company %></p>
        <p class="p-nav-global-name"><%= current_user.name %>様</p>
      </div>
      <li class="p-nav-global_item"><%= link_to 'アカウント設定', edit_user_path(id: current_user.id), class:"p-nav-global_item-link" %></li>
      <li class="p-nav-global_item"><%= link_to 'ログアウト', logout_path, method: :delete, class:'p-nav-global_item-link' %></li>
      <% if current_user.admin? %>
      <li class="p-nav-global_item"><%= link_to '管理者ページ', rails_admin_path, class:"p-nav-global_item-link" %></li>
      <% end %>
    </ul>

  </nav>
</div>

app/views/password_resets/create.html.erb
<h1>PasswordResets#create</h1>
<p>Find me in app/views/password_resets/create.html.erb</p>

app/views/password_resets/edit.html.erb
<div class="login c-area">
  <div class="login-wrap" id="login_form">
    <div class="login-contents">
      <div class="login-title-box">
        <p class="login-title">オンライン資料作成サービス</p>
        <%= image_tag 'logo_blue.svg', {class: 'login-logo'} %>
      </div>
      <%= form_with model:@user, url: password_reset_path(@token), local: true, class: "login-form-box", method: :put do |f| %>
        <dl class="login-item">
          <dt class="login-label">メールアドレス</dt>
          <dd class="login-input"><%= f.text_field :email %></dd>
        </dl>
        <dl class="login-item">
          <dt class="login-label">パスワード</dt>
          <dd class="login-input"><%= f.text_field :password %></dd>
        </dl>
        <dl class="login-item">
          <dt class="login-label">パスワード確認用</dt>
          <dd class="login-input"><%= f.text_field :password_confirmation %></dd>
        </dl>
        <%= f.submit  "更新する", class: "login-button" %>
      <% end %>
    </div>

  </div>
</div>

app/views/password_resets/new.html.erb
<div class="login c-area">
  <div class="login-wrap" id="login_form">
    <div class="login-contents">
      <div class="login-title-box">
        <p class="login-title">オンライン資料作成サービス</p>
        <%= image_tag 'logo_blue.svg', {class: 'login-logo'} %>
      </div>
      <%= form_with url:password_resets_path, local: true, class: "login-form-box", method: :post do |f| %>
        <dl class="login-item">
          <dt class="login-label">メールアドレス</dt>
          <dd class="login-input"><%= f.text_field :email %></dd>
        </dl>
        <%= f.submit  "送信する", class: "login-button" %>
        <%= link_to '戻る', login_path, class:"login-forgot" %>
      <% end %>
    </div>

  </div>
</div>

app/views/password_resets/update.html.erb
<h1>PasswordResets#update</h1>
<p>Find me in app/views/password_resets/update.html.erb</p>

app/views/settings/edit.html.erb
<h2 class="option-title">設定</h2>

<%= form_with model: @setting[0] do |f| %>

  <dl class="option-form">
    <dt class="option-form_title">フォント</dt>
    <dd>
      <%= f.select :font, [
        ["游ゴシック", "游ゴシック"],
        ["メイリオ", "メイリオ"],
        ["Meiryo UI", "Meiryo UI"],
        ["コーポレート・ロゴ", "コーポレート・ロゴ"]
        ], include_blank: current_user.setting.font, class:"option-form_desc" %>
    </dd>
    
  </dl>

  <dl class="option-form">
    <dt class="option-form_title">
      <p class="option-form_title-text">メインカラー</p>
      <input type="color" class="option-form_title-color" id="js-main-pick">
    </dt>
    <dd><%= f.text_field :main_color, class:"option-form_desc", id:"js-main-code", :value => current_user.setting.main_color %></dd>
  </dl>

  <dl class="option-form">
    <dt class="option-form_title">
      <p class="option-form_title-text">アクセントカラー</p>
      <input type="color" class="option-form_title-color" id="js-sub-pick">
    </dt>
    <dd><%= f.text_field :sub_color, class:"option-form_desc", id:"js-sub-code", :value => current_user.setting.sub_color %></dd>
  </dl>

  <%= f.submit "保存する", class:"option-submit" %>

<% end %>

app/views/settings/new.html.erb
<h2 class="option-title">設定</h2>

<%= form_with model: @setting do |f| %>

  <dl class="option-form">
    <dt class="option-form_title">フォント</dt>
    <dd>
      <%= f.select :font, [
        ["游ゴシック", "游ゴシック"],
        ["メイリオ", "メイリオ"],
        ["Meiryo UI", "Meiryo UI"],
        ["コーポレート・ロゴ", "コーポレート・ロゴ"]
        ], include_blank: "選択して下さい", class:"option-form_desc" %>
    </dd>
    
  </dl>

  <dl class="option-form">
    <dt class="option-form_title">
      <p class="option-form_title-text">メインカラー</p>
      <input type="color" class="option-form_title-color" id="js-main-pick">
    </dt>
    <dd><%= f.text_field :main_color, class:"option-form_desc", id:"js-main-code" %></dd>
  </dl>

  <dl class="option-form">
    <dt class="option-form_title">
      <p class="option-form_title-text">アクセントカラー</p>
      <input type="color" class="option-form_title-color" id="js-sub-pick">
    </dt>
    <dd><%= f.text_field :sub_color, class:"option-form_desc", id:"js-sub-code" %></dd>
  </dl>

  <%= f.submit "保存する", class:"option-submit" %>

<% end %>